### VALID POST Request for entry Passage -- Outside of Planned Appointment
POST localhost:8080/api/passages
Content-Type: application/json
Accept: application/json

{
  "licensePlate": "FPQ-520",
  "arrivalTime": "2024-10-16T09:01:00",
  "incoming": true
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 303, "Response status is not 303 SEE OTHER");
    });

%}


### VALID POST Request for add to WAITING QUEUE
POST localhost:8080/add-to-waitingqueue HTTP/1.1
Host: localhost
Content-Type: application/x-www-form-urlencoded


customerName=Vos%2C+Poppe+en+Peeters+CV&rawMaterial=Gips&licensePlate=FPQ-520&simulatedTimeOfRegistration=2024-10-16T09%3A17


### VALID POST Request for entry Passage
POST localhost:8080/api/passages
Content-Type: application/json
Accept: application/json

{
  "licensePlate": "FPQ-520",
  "arrivalTime": "2024-10-16T20:01:00",
  "incoming": true
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201: PASSAGE NOT GRANTED");
    });

%}