### VALID POST Request for entry Passage
POST localhost:8080/api/passages
Content-Type: application/json
Accept: application/json

{
  "licensePlate": "1-TVI-848",
  "arrivalTime": "2024-10-01T08:12:00",
  "incoming": true
}
> {%
    client.global.set("payloadDeliveryId", response.body.payloadDeliveryId)
 %}


### VALID POST Request at weighbridge
POST localhost:8080/api/weighbridge
Content-Type: application/json
Accept: application/json

{

  "payloadDeliveryId": "{{payloadDeliveryId}}",
  "entryWeighing": true
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });

    client.test("Response content-type is json", function() {
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("Directions Message is present", function () {
        client.assert((response.body.message != '' || response.body.message == null), "Message is empty")
    })

    client.test("Ticket is present", function () {
        client.assert((response.body.ticket != null), "Ticket is empty")
    })

    client.test("grossWeight is 20", function() {
        client.assert(response.body.ticket.grossWeightAtArrival == 20.0, "Gross weight body is not 20, as specified in config");
    });

    client.test("netWeight is null", function() {
        client.assert(response.body.ticket.netWeight == null, "Netweight is not null, as it should be in the entry weighing");
    });

%}


