### INVALID POST Request for entry Passage
# @no-redirect
POST localhost:8080/api/passages
Content-Type: application/json
Accept: application/json

{
  "licensePlate": "1-FOX-999",
  "arrivalTime": "2024-10-12T18:12:00"
}

### VALID POST Create Waiting Queue
POST localhost:8080/add-to-waitingqueue HTTP/1.1
Host: localhost
Content-Type: application/x-www-form-urlencoded

customerName=Desmet+NV&rawMaterial=Slak&licensePlate=1-FOX-999&simulatedTimeOfRegistration=2024-10-12T18%3A13

### VALID POST Request for entry Passage
POST localhost:8080/api/passages
Content-Type: application/json
Accept: application/json

{
  "licensePlate": "1-FOX-999",
  "arrivalTime": "2024-10-12T20:01:00"
}